local M = {}

function M.setup(c, set)
	set("Pmenu", { fg = c.fg1, bg = c.bg2 })
	set("PmenuSel", { fg = c.bg0, bg = c.cyan1, bold = true })

	set("CmpItemKindMethod", { fg = c.cyan2, bold = true })
	set("CmpItemKindFunction", { fg = c.cyan2, bold = true })
	set("CmpItemKindConstructor", { fg = c.cyan1 })
	set("CmpItemKindVariable", { fg = c.teal })
	set("CmpItemKindField", { fg = c.teal })
	set("CmpItemKindProperty", { fg = c.teal })
	set("CmpItemKindClass", { fg = c.purple, bold = true })
	set("CmpItemKindInterface", { fg = c.purple })
	set("CmpItemKindStruct", { fg = c.purple })
	set("CmpItemKindEnum", { fg = c.purple })
	set("CmpItemKindEnumMember", { fg = c.blue })
	set("CmpItemKindKeyword", { fg = c.cyan1, bold = true })
	set("CmpItemKindSnippet", { fg = c.ice })
	set("CmpItemKindFile", { fg = c.fg1 })
	set("CmpItemKindFolder", { fg = c.border })

	set("NoiceCompletionItemKindFunction", { link = "CmpItemKindFunction" })
	set("NoiceCompletionItemKindMethod", { link = "CmpItemKindMethod" })
	set("NoiceCompletionItemKindVariable", { link = "CmpItemKindVariable" })
	set("NoiceCompletionItemKindKeyword", { link = "CmpItemKindKeyword" })
	set("NoiceCompletionItemKindProperty", { link = "CmpItemKindProperty" })

	set("NoiceCmdlinePopupBorderSearch", { fg = c.cyan1, bg = "NONE" })
	set("NoiceCmdlinePopupTitleSearch", { fg = c.cyan1, bold = true })
	set("NoiceCmdlinePopupBorder", { fg = c.red_neon, bg = "NONE" })
	set("NoiceCmdlinePopupTitle", { fg = c.red_neon, bold = true })
	set("NoiceCmdline", { fg = c.fg0, bg = c.bg2 })
	set("NoiceCmdlinePrompt", { fg = c.cyan1, bold = true })

	set("BufferLineBufferSelected", { fg = c.white, bg = c.bg2, bold = true })
	set("BufferLineBuffer", { fg = c.fg2, bg = c.bg1 })
	set("BufferLineBackground", { fg = c.fg2, bg = c.bg1 })
	set("BufferLineFill", { bg = c.bg0 })
	set("BufferLineSeparator", { fg = c.bg0, bg = c.bg1 })
	set("BufferLineSeparatorSelected", { fg = c.bg0, bg = c.bg2 })
	set("BufferLineModified", { fg = c.blue, bg = c.bg1 })
	set("BufferLineModifiedSelected", { fg = c.cyan1, bg = c.bg2, bold = true })

	set("lualine_a_normal", { fg = c.bg0, bg = c.cyan1, bold = true })
	set("lualine_a_insert", { fg = c.bg0, bg = c.teal, bold = true })
	set("lualine_a_visual", { fg = c.bg0, bg = c.purple, bold = true })
	set("lualine_a_replace", { fg = c.bg0, bg = c.blue, bold = true })
	set("lualine_a_command", { fg = c.bg0, bg = c.ice, bold = true })
	set("lualine_b_normal", { fg = c.cyan1, bg = c.bg2 })
	set("lualine_b_insert", { fg = c.teal, bg = c.bg2 })
	set("lualine_b_visual", { fg = c.purple, bg = c.bg2 })
	set("lualine_c_normal", { fg = c.fg1, bg = c.bg1 })
	set("lualine_c_insert", { fg = c.fg1, bg = c.bg1 })

	set("SnacksDashboardHeader", { fg = c.cyan1 })
	set("SnacksDashboardTitle", { fg = c.cyan2, bold = true })
	set("SnacksDashboardIcon", { fg = c.ice })
	set("SnacksDashboardDesc", { fg = c.fg2 })
	set("SnacksDashboardKey", { fg = c.purple })
	set("SnacksDashboardFile", { fg = c.fg1 })
	set("SnacksDashboardDir", { fg = c.fg2 })

	set("LazyNormal", { fg = c.fg0, bg = c.bg2 })
	set("LazyButton", { fg = c.fg1, bg = c.bg3 })
	set("LazyButtonActive", { fg = c.white, bg = c.deep, bold = true })
	set("LazyH1", { fg = c.bg0, bg = c.cyan1, bold = true })

	set("FlashMatch", { fg = c.ice, bg = c.deep, bold = true })
	set("FlashCurrent", { fg = c.bg0, bg = c.cyan1, bold = true })
	set("FlashLabel", { fg = c.bg0, bg = c.pink, bold = true })
	set("FlashBackdrop", { fg = c.fg2 })
end

return M
